name: 🚀 Deploy File to cPanel on push
on:
    push:
        branches:
            - dev

jobs:
    FTP-Deploy-Action:
        name: 🎉 Deploy
        runs-on: ubuntu-latest

        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2

            - name: 📂 Sync folders and files to the server
              uses: SamKirkland/FTP-Deploy-Action@4.3.3
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  server-dir: /allyapp/
                  fail-on-fatal: true
      
